'use client';
import Image from 'next/image';
import {useCallback,useEffect,useRef,useState,type CSSProperties} from 'react';
import {AGENTS,DEFAULT_SETTINGS,EXPLORER,type Desk,type Settings,type TradingAgent} from '@/lib/trading/shared';
import {withdrawalMessage} from '@/lib/trading/withdrawal';
import s from './TradingDesk.module.css';
type Provider={request:(p:{method:string;params?:unknown[]})=>Promise<unknown>};
type Wallet={uuid:string;name:string;provider:Provider};
type FullDesk=Desk;
const amount=(v:string)=>Number(v).toLocaleString(undefined,{maximumFractionDigits:6});
const short=(v:string)=>v.slice(0,6)+'…'+v.slice(-4);
async function api(path:string,method='GET',data?:unknown){const r=await fetch('/api/jolly/trading/'+path,{method,headers:{'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{}),cache:'no-store'});const body=await r.json();if(!r.ok)throw new Error(body.error||'Please try again.');return body;}
function face(color:string){return <span className={s.face} style={{'--accent':color} as CSSProperties}><Image src="/jolly-reference.webp" alt="" width={180} height={180}/></span>;}
export function TradingDesk({signInUrl}:{signInUrl:string}){
 const [desk,setDesk]=useState<FullDesk|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [template,setTemplate]=useState('scout'),[mode,setMode]=useState<'paper'|'live'>('paper'),[selected,setSelected]=useState<string|null>(null),[settings,setSettings]=useState<Settings>({...DEFAULT_SETTINGS});
 const [wallets,setWallets]=useState<Wallet[]>([]),[walletChoice,setWalletChoice]=useState(''),[panel,setPanel]=useState<'fund'|'withdraw'|null>(null),[transferAmount,setTransferAmount]=useState(''),[acceptRisk,setAcceptRisk]=useState(false);
 const operation=useRef<{id:string;agent:string;amount:string;expires:number}|null>(null);
 const active=desk?.agents.find(a=>a.id===selected)||null;
 const load=useCallback(async()=>{const d=await api('status');setDesk(d);return d as FullDesk;},[]);
 useEffect(()=>{let alive=true;const poll=()=>{if(!document.hidden)load().catch(e=>{if(alive)setError(e.message);});};poll();const interval=setInterval(poll,12000);return()=>{alive=false;clearInterval(interval);};},[load]);
 useEffect(()=>{function announce(e:Event){const w=(e as CustomEvent).detail;if(w?.info?.uuid&&w.provider?.request)setWallets(old=>old.some(x=>x.uuid===w.info.uuid)?old:[...old,{uuid:w.info.uuid,name:w.info.name,provider:w.provider}]);}
 window.addEventListener('eip6963:announceProvider',announce);window.dispatchEvent(new Event('eip6963:requestProvider'));
 const injected=(window as unknown as {ethereum?:Provider}).ethereum;if(injected)setWallets(old=>old.length?old:[{uuid:'injected',name:'Browser wallet',provider:injected}]);
 return()=>window.removeEventListener('eip6963:announceProvider',announce);},[]);
 function choose(a:TradingAgent|null){setSelected(a?.id||null);setTemplate(a?.template||'scout');setMode(a?.mode||'paper');setSettings(a?{...a.settings}:{...DEFAULT_SETTINGS});setPanel(null);setAcceptRisk(false);setNotice('');setError('');}
 async function task(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setNotice('');try{await fn();await load();}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 function provider(){const w=wallets.find(x=>x.uuid===walletChoice)||wallets[0];if(!w)throw new Error('Open Jolly in the MetaMask or Trust Wallet browser, or install a browser wallet.');return w.provider;}
 async function connect(){await task(async()=>{const p=provider(),accounts=await p.request({method:'eth_requestAccounts'}) as string[];const address=accounts[0];const challenge=await api('auth','POST',{address});const message='0x'+Array.from(new TextEncoder().encode(challenge.message),(v)=>v.toString(16).padStart(2,'0')).join('');const signature=await p.request({method:'personal_sign',params:[message,address]});await api('auth','POST',{address,signature});choose(null);setNotice('Wallet ownership verified.');});}
 async function chainWallet(){const p=provider();const accounts=await p.request({method:'eth_requestAccounts'}) as string[];try{await p.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x1237'}]});}catch(e){if((e as {code?:number}).code!==4902)throw e;await p.request({method:'wallet_addEthereumChain',params:[{chainId:'0x1237',chainName:'Robinhood Chain',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:['https://rpc.mainnet.chain.robinhood.com'],blockExplorerUrls:[EXPLORER]}]});}
 if(await p.request({method:'eth_chainId'})!=='0x1237')throw new Error('Switch your wallet to Robinhood Chain.');return {p,address:accounts[0]};}
 async function action(action:string,extra:Record<string,unknown>={}){if(!active)return;await task(async()=>{await api('agents/'+active.id,'POST',{action,...extra});setNotice(action==='pause'?'New entries paused. Existing exit rules remain active.':'Agent updated.');});}
 async function save(){await task(async()=>{if(active){await api('agents/'+active.id,'POST',{action:'settings',settings});setNotice('Limits saved.');}else{const r=await api('agents','POST',{template,mode,settings});setSelected(r.id);setNotice(mode==='paper'?'Practice agent created with simulated ETH.':'Agent created. Set up its wallet next.');}});}
 async function transfer(){if(!active)return;await task(async()=>{if(!/^(0|[1-9]\d{0,3})(\.\d{1,8})?$/.test(transferAmount)||Number(transferAmount)<=0)throw new Error('Enter an ETH amount.');const {p,address}=await chainWallet();if(panel==='fund'){
 const [whole,decimal='']=transferAmount.split('.'),wei=BigInt(whole)*10n**18n+BigInt(decimal.padEnd(18,'0'));
 const hash=await p.request({method:'eth_sendTransaction',params:[{from:address,to:active.walletAddress,value:'0x'+wei.toString(16)}]});setNotice('Deposit submitted: '+String(hash)+'. Your balance updates after confirmation.');
 }else{
 let op=operation.current;if(!op||op.agent!==active.id||op.amount!==transferAmount||op.expires<Date.now()){op={id:crypto.randomUUID(),agent:active.id,amount:transferAmount,expires:Date.now()+240000};operation.current=op;}
 const message=withdrawalMessage(active.id,address,transferAmount,op.id,op.expires);const hex='0x'+Array.from(new TextEncoder().encode(message),v=>v.toString(16).padStart(2,'0')).join('');const signature=await p.request({method:'personal_sign',params:[hex,address]});
 const r=await api('agents/'+active.id,'POST',{action:'withdraw',amount:transferAmount,address,requestId:op.id,expires:op.expires,signature});setNotice('Withdrawal submitted'+(r.txHash?': '+r.txHash:'. Check your activity.'));operation.current=null;
 }setTransferAmount('');setPanel(null);});}
 const current=AGENTS.find(a=>a.id===template)!;
 const field=(key:keyof Settings,label:string,step:string|number='any')=><label key={key}>{label}<input type="number" inputMode="decimal" step={step} min="0" value={settings[key]} disabled={busy||active?.status==='running'} onChange={e=>setSettings(old=>({...old,[key]:typeof DEFAULT_SETTINGS[key]==='number'?Number(e.target.value):e.target.value}))}/></label>;
 return <main className={s.page}>
  <header className={s.hero}><div><span className={s.eyebrow}>A little Jolly. Your own trading rules.</span><h1>Meet your trading agent.</h1><p>Pick a companion, give it a budget, and stay in control.<br/>Pons tokens on Robinhood Chain.</p></div><div className={s.heroFace}>{face(current.color)}<span>Built around your limits</span></div></header>
  <div className={s.toolbar}><div className={s.tabs}><button className={mode==='paper'?s.tabActive:''} onClick={()=>{choose(null);setMode('paper');}}>Practice</button><button className={mode==='live'?s.tabActive:''} onClick={()=>{choose(null);setMode('live');}}>Live wallets</button></div><span className={s.network}><i/>Robinhood Chain · ETH</span></div>
  {error&&<div className={s.error} role="alert">{error}</div>}{notice&&<div className={s.notice} role="status">{notice}</div>}
  {!desk&&<p aria-live="polite">Loading your trading desk…</p>}
  {desk&&!desk.authenticated&&<section className={s.login}><div><h2>Your agent, your account.</h2><p>Sign in to save your limits and create a practice agent.</p></div><div className={s.actions}><a href={signInUrl} className={s.primary}>Continue with X</a>{wallets.length>1&&<select aria-label="Wallet provider" value={walletChoice} onChange={e=>setWalletChoice(e.target.value)}><option value="">Choose wallet</option>{wallets.map(w=><option key={w.uuid} value={w.uuid}>{w.name}</option>)}</select>}<button disabled={busy} onClick={connect}>Connect wallet</button></div></section>}
  {desk?.authenticated&&<div className={s.accountBar}><span>Signed in as <strong>{desk.identity?.startsWith('0x')?short(desk.identity):desk.identity}</strong></span><span>{desk.workerOnline?'● Engine online':'○ Engine connecting'}</span></div>}
  {mode==='live'&&!desk?.liveReady&&<div className={s.setup}><strong>Live wallets are being connected.</strong><span>You can choose your agent and explore its limits now. Creating a real wallet and depositing funds will become available once managed signing is configured and verified.</span></div>}
  {!!desk?.agents.length&&<div className={s.agentSwitcher}><label>My agents <select value={selected||''} onChange={e=>choose(desk.agents.find(a=>a.id===e.target.value)||null)}><option value="">Create an agent</option>{desk.agents.map(a=><option key={a.id} value={a.id}>{AGENTS.find(t=>t.id===a.template)?.name} · {a.mode==='paper'?'Practice':'Live'}</option>)}</select></label><button onClick={()=>choose(null)}>+ New agent</button></div>}
  <div className={s.grid}><section className={s.main}>
   <div className={s.sectionHeading}><span>01</span><h2>Choose your Jolly</h2></div>
   <div className={s.cards}>{AGENTS.map(a=><button key={a.id} disabled={!!active||busy} aria-pressed={template===a.id} className={`${s.card} ${template===a.id?s.selected:''}`} style={{'--accent':a.color} as CSSProperties} onClick={()=>setTemplate(a.id)}>{face(a.color)}<strong>{a.name}</strong><p>{a.description}</p><small>{a.id==='patient'?'More time between entries':a.id==='momentum'?'Price momentum checks':'Fresh launch discovery'}</small></button>)}</div>
   {active&&<><div className={s.metrics}><div><span>{active.mode==='paper'?'Practice balance':'Available ETH'}</span><strong>{amount(active.cashEth)} <small>ETH</small></strong></div><div><span>Agent equity</span><strong>{amount(active.equityEth)} <small>ETH</small></strong></div><div><span>Today’s P&amp;L</span><strong className={Number(active.dailyPnlEth)<0?s.negative:s.positive}>{amount(active.dailyPnlEth)} <small>ETH</small></strong></div></div><p className={s.caption}>{active.mode==='paper'?'Simulated ETH and fills. No real funds are used.':'ETH values include open positions at their last available exit quote.'} Daily limits reset at 00:00 UTC.</p></>}
   <section className={s.activity}><div className={s.sectionHeading}><span>03</span><h2>Positions &amp; activity</h2></div>
    {!active?<div className={s.empty}><span>✧</span><h3>A fresh start for your Jolly.</h3><p>Create an agent to see its positions, decisions, and trades here.</p></div>:<><div className={s.statusLine}><b className={s.badge}>{active.status.replace('_',' ')}</b><span>{active.blockedReason||'Set your limits, then start your agent.'}</span></div>
    {desk?.positions.filter(p=>p.agentId===active.id).map(p=><div key={p.id} className={s.position}><a href={EXPLORER+'/token/'+p.token} target="_blank" rel="noreferrer"><strong>{p.symbol}</strong><small>{short(p.token)}</small></a><div><span>{amount(p.markEth)} ETH</span><small>Entry {amount(p.entryEth)} ETH</small></div><button disabled={busy} onClick={()=>action('close',{positionId:p.id})}>Close position</button></div>)}
    {!desk?.positions.some(p=>p.agentId===active.id)&&<p className={s.caption}>No open positions. Your agent only enters when its checks pass.</p>}
    <div className={s.history}>{desk?.orders.filter(o=>o.agentId===active.id).map(o=><div key={o.id}><span><b>{o.kind}</b> {o.symbol||'ETH'}<small>{new Date(o.createdAt).toLocaleString()}</small></span><span>{o.status}{o.txHash&&<a href={EXPLORER+'/tx/'+o.txHash} target="_blank" rel="noreferrer">View transaction ↗</a>}{!o.txHash&&active.mode==='paper'&&<small>Practice only</small>}</span></div>)}</div></>}
   </section>
  </section><aside className={s.sidebar}>
   <section className={s.panel}><div className={s.sectionHeading}><span>02</span><h2>Your rules</h2></div><p>Limits are checked before every entry. The AI cannot raise them.</p><div className={s.fields}>
    {field('budgetEth','Total allocation · ETH')}{field('tradeEth','Per trade · ETH')}{field('dailySpendEth','Daily buy budget · ETH')}{field('dailyLossEth','Daily stop-loss · ETH')}{field('maxTrades','Max buys per day',1)}{field('maxPositions','Max open positions',1)}{field('stopLossPct','Position stop-loss · %',1)}{field('takeProfitPct','Take-profit · %',1)}{field('slippageBps','Max slippage · bps',10)}{field('maxHoldMinutes','Max hold · minutes',1)}
   </div><p className={s.caption}>100 bps = 1% slippage. A daily loss stop blocks buys and attempts exits. Fast price moves and thin liquidity can cause larger losses.</p>
   <button className={s.primary} disabled={busy||!desk?.authenticated||active?.status==='running'||(mode==='live'&&!desk.liveReady)} onClick={save}>{active?'Save limits':mode==='paper'?'Create practice agent':'Create live agent'}</button>
   {active&&<div className={s.runControls}>{active.mode==='live'&&active.status!=='running'&&<label className={s.check}><input type="checkbox" checked={acceptRisk} onChange={e=>setAcceptRisk(e.target.checked)}/>I authorise automatic trades within these limits and understand funds can be lost.</label>}<button className={s.primary} disabled={busy||active.status==='running'||(active.mode==='live'&&!acceptRisk)} onClick={()=>action('start',{acceptRisk})}>Start {active.mode==='paper'?'practice':'trading'}</button><button disabled={busy||active.status!=='running'} onClick={()=>action('pause')}>Pause entries</button><small>Exit rules keep running while entries are paused.</small></div>}
   </section>
   <section className={s.panel}><div className={s.walletTitle}><span>◈</span><h2>Agent wallet</h2><b>{mode==='paper'?'Practice':'Managed'}</b></div>
    {mode==='paper'?<p>Practice mode uses a simulated balance equal to your starting allocation. No deposit is needed.</p>:active?.walletAddress?<><p>A separate wallet managed by Jolly’s server. Send only ETH on Robinhood Chain.</p><code className={s.address}>{active.walletAddress}</code><div className={s.actions}><button onClick={()=>task(async()=>{await navigator.clipboard.writeText(active.walletAddress!);setNotice('Wallet address copied.');})}>Copy address</button><button disabled={busy} onClick={()=>action('refresh')}>Refresh balance</button></div><div className={s.actions}><button onClick={()=>{setPanel('fund');setTransferAmount('');}}>Add ETH</button><button disabled={active.status==='running'} onClick={()=>{setPanel('withdraw');setTransferAmount('');}}>Withdraw</button></div>{panel&&<div className={s.transfer}><label>{panel==='fund'?'Deposit':'Withdraw'} amount · ETH<input type="number" min="0" step="0.001" value={transferAmount} onChange={e=>setTransferAmount(e.target.value)}/></label><p>{panel==='fund'?'Your personal wallet will ask you to confirm the deposit.':'Connect your receiving wallet and sign the withdrawal details. Leave ETH for network fees.'}</p><button className={s.primary} disabled={busy} onClick={transfer}>{panel==='fund'?'Deposit from my wallet':'Sign withdrawal'}</button><button onClick={()=>setPanel(null)}>Cancel</button></div>}</>:<><p>Your agent gets its own wallet, managed by Jolly through Privy. Jolly’s backend signs approved trades; the AI never receives private keys.</p><button disabled={busy||!active||!desk?.liveReady} onClick={()=>action('wallet')}>{desk?.liveReady?'Create agent wallet':'Awaiting wallet setup'}</button></>}
   </section>
  </aside></div>
  <p className={s.footerNote}>Jolly trades supported native-ETH Pons pools. Strategies can lose money. Practice results use live quotes with modelled slippage and fees; they do not predict live results.</p>
 </main>;
}
