import assert from 'node:assert/strict';
import {privateKeyToAccount,generatePrivateKey} from 'viem/accounts';
import {writeFileSync,readFileSync,existsSync} from 'node:fs';
import {DEFAULT_SETTINGS} from '../lib/trading/shared';
const origin='https://jollybot.lol',key=(existsSync('/tmp/jolly-rh-verification-wallet')?readFileSync('/tmp/jolly-rh-verification-wallet','utf8'):generatePrivateKey()) as `0x${string}`,wallet=privateKeyToAccount(key);
let cookie='';
async function request(path:string,data?:unknown){const r=await fetch(origin+'/api/jolly/trading/'+path,{method:data?'POST':'GET',headers:{'Content-Type':'application/json',Origin:origin,...(cookie?{Cookie:cookie}:{})},...(data?{body:JSON.stringify(data)}:{}),signal:AbortSignal.timeout(60000)});return {r,body:await r.json()};}
async function main(){writeFileSync('/tmp/jolly-rh-verification-wallet',key,{mode:0o600});let q=await request('auth',{address:wallet.address});assert.equal(q.r.status,200);cookie=q.r.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');const signature=await wallet.signMessage({message:q.body.message});q=await request('auth',{address:wallet.address,signature});assert.equal(q.r.status,200);cookie=q.r.headers.getSetCookie().filter(c=>c.startsWith('jolly_trade_session=')).map(c=>c.split(';')[0]).join('; ');console.log('PASS Robinhood wallet authentication');const existing=(await request('status')).body.agents;q=existing.length?{r:{status:200} as Response,body:{id:existing[0].id}}:await request('agents',{template:'scout',mode:'paper',settings:DEFAULT_SETTINGS,modelId:'claude-haiku-4-5',shareDiscussions:false,discussionEnabled:false});assert.equal(q.r.status,200);const id=q.body.id;q=await request('agents/'+id,{action:'settings',settings:DEFAULT_SETTINGS,modelId:'deepseek-v4-flash',shareDiscussions:false,discussionEnabled:false});assert.equal(q.r.status,200);q=await request('status');assert.equal(q.body.agents.find((a:any)=>a.id===id).modelId,'deepseek-v4-flash');assert.equal(q.body.agents.find((a:any)=>a.id===id).discussionEnabled,false);console.log('PASS Robinhood agent creation and selected-model persistence');const f=await fetch(origin+'/api/jolly/trading/feed',{headers:{Cookie:cookie},signal:AbortSignal.timeout(65000)});assert.equal(f.status,200);const reader=f.body!.getReader();const first=await reader.read();assert(new TextDecoder().decode(first.value).includes('READY'));await reader.cancel();console.log('PASS private real-time discussion stream; no funds or orders submitted');}
main().then(()=>process.exit(0)).catch(e=>{console.error(e.message);process.exit(1)});
